// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userdata.proto

package com.tt.mariage.server.proto;

public final class UserDataProtos {
  private UserDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BlobOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string mail = 1;
    boolean hasMail();
    String getMail();
    
    // repeated .tutorial.Blob.Person person = 2;
    java.util.List<com.tt.mariage.server.proto.UserDataProtos.Blob.Person> 
        getPersonList();
    com.tt.mariage.server.proto.UserDataProtos.Blob.Person getPerson(int index);
    int getPersonCount();
    java.util.List<? extends com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder> 
        getPersonOrBuilderList();
    com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder getPersonOrBuilder(
        int index);
    
    // required bool isBookHotel = 3;
    boolean hasIsBookHotel();
    boolean getIsBookHotel();
    
    // optional string arrivalDate = 4;
    boolean hasArrivalDate();
    String getArrivalDate();
    
    // optional string departureDate = 5;
    boolean hasDepartureDate();
    String getDepartureDate();
    
    // required bool hasCar = 6;
    boolean hasHasCar();
    boolean getHasCar();
    
    // optional string freePlaces = 7;
    boolean hasFreePlaces();
    String getFreePlaces();
    
    // optional string phoneNumber = 8;
    boolean hasPhoneNumber();
    String getPhoneNumber();
    
    // optional string otherInfo = 9;
    boolean hasOtherInfo();
    String getOtherInfo();
  }
  public static final class Blob extends
      com.google.protobuf.GeneratedMessage
      implements BlobOrBuilder {
    // Use Blob.newBuilder() to construct.
    private Blob(Builder builder) {
      super(builder);
    }
    private Blob(boolean noInit) {}
    
    private static final Blob defaultInstance;
    public static Blob getDefaultInstance() {
      return defaultInstance;
    }
    
    public Blob getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_fieldAccessorTable;
    }
    
    public interface PersonOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string lastName = 1;
      boolean hasLastName();
      String getLastName();
      
      // required string firstName = 2;
      boolean hasFirstName();
      String getFirstName();
      
      // required bool isInfant = 3;
      boolean hasIsInfant();
      boolean getIsInfant();
      
      // optional string menu = 4;
      boolean hasMenu();
      String getMenu();
    }
    public static final class Person extends
        com.google.protobuf.GeneratedMessage
        implements PersonOrBuilder {
      // Use Person.newBuilder() to construct.
      private Person(Builder builder) {
        super(builder);
      }
      private Person(boolean noInit) {}
      
      private static final Person defaultInstance;
      public static Person getDefaultInstance() {
        return defaultInstance;
      }
      
      public Person getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_Person_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_Person_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string lastName = 1;
      public static final int LASTNAME_FIELD_NUMBER = 1;
      private java.lang.Object lastName_;
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getLastName() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            lastName_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string firstName = 2;
      public static final int FIRSTNAME_FIELD_NUMBER = 2;
      private java.lang.Object firstName_;
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getFirstName() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            firstName_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required bool isInfant = 3;
      public static final int ISINFANT_FIELD_NUMBER = 3;
      private boolean isInfant_;
      public boolean hasIsInfant() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsInfant() {
        return isInfant_;
      }
      
      // optional string menu = 4;
      public static final int MENU_FIELD_NUMBER = 4;
      private java.lang.Object menu_;
      public boolean hasMenu() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getMenu() {
        java.lang.Object ref = menu_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            menu_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getMenuBytes() {
        java.lang.Object ref = menu_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          menu_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        lastName_ = "";
        firstName_ = "";
        isInfant_ = false;
        menu_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasLastName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFirstName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasIsInfant()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getLastNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getFirstNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBool(3, isInfant_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, getMenuBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getLastNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getFirstNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(3, isInfant_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, getMenuBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.tt.mariage.server.proto.UserDataProtos.Blob.Person parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.tt.mariage.server.proto.UserDataProtos.Blob.Person prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_Person_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_Person_fieldAccessorTable;
        }
        
        // Construct using com.tt.mariage.server.proto.UserDataProtos.Blob.Person.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          lastName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          firstName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          isInfant_ = false;
          bitField0_ = (bitField0_ & ~0x00000004);
          menu_ = "";
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tt.mariage.server.proto.UserDataProtos.Blob.Person.getDescriptor();
        }
        
        public com.tt.mariage.server.proto.UserDataProtos.Blob.Person getDefaultInstanceForType() {
          return com.tt.mariage.server.proto.UserDataProtos.Blob.Person.getDefaultInstance();
        }
        
        public com.tt.mariage.server.proto.UserDataProtos.Blob.Person build() {
          com.tt.mariage.server.proto.UserDataProtos.Blob.Person result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.tt.mariage.server.proto.UserDataProtos.Blob.Person buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.tt.mariage.server.proto.UserDataProtos.Blob.Person result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.tt.mariage.server.proto.UserDataProtos.Blob.Person buildPartial() {
          com.tt.mariage.server.proto.UserDataProtos.Blob.Person result = new com.tt.mariage.server.proto.UserDataProtos.Blob.Person(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.lastName_ = lastName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.firstName_ = firstName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.isInfant_ = isInfant_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.menu_ = menu_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tt.mariage.server.proto.UserDataProtos.Blob.Person) {
            return mergeFrom((com.tt.mariage.server.proto.UserDataProtos.Blob.Person)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.tt.mariage.server.proto.UserDataProtos.Blob.Person other) {
          if (other == com.tt.mariage.server.proto.UserDataProtos.Blob.Person.getDefaultInstance()) return this;
          if (other.hasLastName()) {
            setLastName(other.getLastName());
          }
          if (other.hasFirstName()) {
            setFirstName(other.getFirstName());
          }
          if (other.hasIsInfant()) {
            setIsInfant(other.getIsInfant());
          }
          if (other.hasMenu()) {
            setMenu(other.getMenu());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasLastName()) {
            
            return false;
          }
          if (!hasFirstName()) {
            
            return false;
          }
          if (!hasIsInfant()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                lastName_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                firstName_ = input.readBytes();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                isInfant_ = input.readBool();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                menu_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string lastName = 1;
        private java.lang.Object lastName_ = "";
        public boolean hasLastName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getLastName() {
          java.lang.Object ref = lastName_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            lastName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setLastName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          lastName_ = value;
          onChanged();
          return this;
        }
        public Builder clearLastName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          lastName_ = getDefaultInstance().getLastName();
          onChanged();
          return this;
        }
        void setLastName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          lastName_ = value;
          onChanged();
        }
        
        // required string firstName = 2;
        private java.lang.Object firstName_ = "";
        public boolean hasFirstName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getFirstName() {
          java.lang.Object ref = firstName_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            firstName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setFirstName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          firstName_ = value;
          onChanged();
          return this;
        }
        public Builder clearFirstName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          firstName_ = getDefaultInstance().getFirstName();
          onChanged();
          return this;
        }
        void setFirstName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          firstName_ = value;
          onChanged();
        }
        
        // required bool isInfant = 3;
        private boolean isInfant_ ;
        public boolean hasIsInfant() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public boolean getIsInfant() {
          return isInfant_;
        }
        public Builder setIsInfant(boolean value) {
          bitField0_ |= 0x00000004;
          isInfant_ = value;
          onChanged();
          return this;
        }
        public Builder clearIsInfant() {
          bitField0_ = (bitField0_ & ~0x00000004);
          isInfant_ = false;
          onChanged();
          return this;
        }
        
        // optional string menu = 4;
        private java.lang.Object menu_ = "";
        public boolean hasMenu() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public String getMenu() {
          java.lang.Object ref = menu_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            menu_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setMenu(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          menu_ = value;
          onChanged();
          return this;
        }
        public Builder clearMenu() {
          bitField0_ = (bitField0_ & ~0x00000008);
          menu_ = getDefaultInstance().getMenu();
          onChanged();
          return this;
        }
        void setMenu(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000008;
          menu_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:tutorial.Blob.Person)
      }
      
      static {
        defaultInstance = new Person(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:tutorial.Blob.Person)
    }
    
    private int bitField0_;
    // required string mail = 1;
    public static final int MAIL_FIELD_NUMBER = 1;
    private java.lang.Object mail_;
    public boolean hasMail() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getMail() {
      java.lang.Object ref = mail_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          mail_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getMailBytes() {
      java.lang.Object ref = mail_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        mail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .tutorial.Blob.Person person = 2;
    public static final int PERSON_FIELD_NUMBER = 2;
    private java.util.List<com.tt.mariage.server.proto.UserDataProtos.Blob.Person> person_;
    public java.util.List<com.tt.mariage.server.proto.UserDataProtos.Blob.Person> getPersonList() {
      return person_;
    }
    public java.util.List<? extends com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder> 
        getPersonOrBuilderList() {
      return person_;
    }
    public int getPersonCount() {
      return person_.size();
    }
    public com.tt.mariage.server.proto.UserDataProtos.Blob.Person getPerson(int index) {
      return person_.get(index);
    }
    public com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder getPersonOrBuilder(
        int index) {
      return person_.get(index);
    }
    
    // required bool isBookHotel = 3;
    public static final int ISBOOKHOTEL_FIELD_NUMBER = 3;
    private boolean isBookHotel_;
    public boolean hasIsBookHotel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public boolean getIsBookHotel() {
      return isBookHotel_;
    }
    
    // optional string arrivalDate = 4;
    public static final int ARRIVALDATE_FIELD_NUMBER = 4;
    private java.lang.Object arrivalDate_;
    public boolean hasArrivalDate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getArrivalDate() {
      java.lang.Object ref = arrivalDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          arrivalDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getArrivalDateBytes() {
      java.lang.Object ref = arrivalDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        arrivalDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string departureDate = 5;
    public static final int DEPARTUREDATE_FIELD_NUMBER = 5;
    private java.lang.Object departureDate_;
    public boolean hasDepartureDate() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getDepartureDate() {
      java.lang.Object ref = departureDate_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          departureDate_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDepartureDateBytes() {
      java.lang.Object ref = departureDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        departureDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required bool hasCar = 6;
    public static final int HASCAR_FIELD_NUMBER = 6;
    private boolean hasCar_;
    public boolean hasHasCar() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public boolean getHasCar() {
      return hasCar_;
    }
    
    // optional string freePlaces = 7;
    public static final int FREEPLACES_FIELD_NUMBER = 7;
    private java.lang.Object freePlaces_;
    public boolean hasFreePlaces() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public String getFreePlaces() {
      java.lang.Object ref = freePlaces_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          freePlaces_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFreePlacesBytes() {
      java.lang.Object ref = freePlaces_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        freePlaces_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string phoneNumber = 8;
    public static final int PHONENUMBER_FIELD_NUMBER = 8;
    private java.lang.Object phoneNumber_;
    public boolean hasPhoneNumber() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getPhoneNumber() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phoneNumber_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhoneNumberBytes() {
      java.lang.Object ref = phoneNumber_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phoneNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string otherInfo = 9;
    public static final int OTHERINFO_FIELD_NUMBER = 9;
    private java.lang.Object otherInfo_;
    public boolean hasOtherInfo() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public String getOtherInfo() {
      java.lang.Object ref = otherInfo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          otherInfo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getOtherInfoBytes() {
      java.lang.Object ref = otherInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        otherInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      mail_ = "";
      person_ = java.util.Collections.emptyList();
      isBookHotel_ = false;
      arrivalDate_ = "";
      departureDate_ = "";
      hasCar_ = false;
      freePlaces_ = "";
      phoneNumber_ = "";
      otherInfo_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMail()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsBookHotel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHasCar()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPersonCount(); i++) {
        if (!getPerson(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMailBytes());
      }
      for (int i = 0; i < person_.size(); i++) {
        output.writeMessage(2, person_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(3, isBookHotel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, getArrivalDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(5, getDepartureDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(6, hasCar_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(7, getFreePlacesBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getPhoneNumberBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(9, getOtherInfoBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMailBytes());
      }
      for (int i = 0; i < person_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, person_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isBookHotel_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getArrivalDateBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getDepartureDateBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, hasCar_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getFreePlacesBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getPhoneNumberBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getOtherInfoBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.tt.mariage.server.proto.UserDataProtos.Blob parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.tt.mariage.server.proto.UserDataProtos.Blob prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.tt.mariage.server.proto.UserDataProtos.BlobOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tt.mariage.server.proto.UserDataProtos.internal_static_tutorial_Blob_fieldAccessorTable;
      }
      
      // Construct using com.tt.mariage.server.proto.UserDataProtos.Blob.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPersonFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        mail_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          personBuilder_.clear();
        }
        isBookHotel_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        arrivalDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        departureDate_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        hasCar_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        freePlaces_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        phoneNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000080);
        otherInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tt.mariage.server.proto.UserDataProtos.Blob.getDescriptor();
      }
      
      public com.tt.mariage.server.proto.UserDataProtos.Blob getDefaultInstanceForType() {
        return com.tt.mariage.server.proto.UserDataProtos.Blob.getDefaultInstance();
      }
      
      public com.tt.mariage.server.proto.UserDataProtos.Blob build() {
        com.tt.mariage.server.proto.UserDataProtos.Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.tt.mariage.server.proto.UserDataProtos.Blob buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.tt.mariage.server.proto.UserDataProtos.Blob result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.tt.mariage.server.proto.UserDataProtos.Blob buildPartial() {
        com.tt.mariage.server.proto.UserDataProtos.Blob result = new com.tt.mariage.server.proto.UserDataProtos.Blob(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mail_ = mail_;
        if (personBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            person_ = java.util.Collections.unmodifiableList(person_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.person_ = person_;
        } else {
          result.person_ = personBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isBookHotel_ = isBookHotel_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.arrivalDate_ = arrivalDate_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000008;
        }
        result.departureDate_ = departureDate_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000010;
        }
        result.hasCar_ = hasCar_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000020;
        }
        result.freePlaces_ = freePlaces_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000040;
        }
        result.phoneNumber_ = phoneNumber_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000080;
        }
        result.otherInfo_ = otherInfo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tt.mariage.server.proto.UserDataProtos.Blob) {
          return mergeFrom((com.tt.mariage.server.proto.UserDataProtos.Blob)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.tt.mariage.server.proto.UserDataProtos.Blob other) {
        if (other == com.tt.mariage.server.proto.UserDataProtos.Blob.getDefaultInstance()) return this;
        if (other.hasMail()) {
          setMail(other.getMail());
        }
        if (personBuilder_ == null) {
          if (!other.person_.isEmpty()) {
            if (person_.isEmpty()) {
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePersonIsMutable();
              person_.addAll(other.person_);
            }
            onChanged();
          }
        } else {
          if (!other.person_.isEmpty()) {
            if (personBuilder_.isEmpty()) {
              personBuilder_.dispose();
              personBuilder_ = null;
              person_ = other.person_;
              bitField0_ = (bitField0_ & ~0x00000002);
              personBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPersonFieldBuilder() : null;
            } else {
              personBuilder_.addAllMessages(other.person_);
            }
          }
        }
        if (other.hasIsBookHotel()) {
          setIsBookHotel(other.getIsBookHotel());
        }
        if (other.hasArrivalDate()) {
          setArrivalDate(other.getArrivalDate());
        }
        if (other.hasDepartureDate()) {
          setDepartureDate(other.getDepartureDate());
        }
        if (other.hasHasCar()) {
          setHasCar(other.getHasCar());
        }
        if (other.hasFreePlaces()) {
          setFreePlaces(other.getFreePlaces());
        }
        if (other.hasPhoneNumber()) {
          setPhoneNumber(other.getPhoneNumber());
        }
        if (other.hasOtherInfo()) {
          setOtherInfo(other.getOtherInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMail()) {
          
          return false;
        }
        if (!hasIsBookHotel()) {
          
          return false;
        }
        if (!hasHasCar()) {
          
          return false;
        }
        for (int i = 0; i < getPersonCount(); i++) {
          if (!getPerson(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              mail_ = input.readBytes();
              break;
            }
            case 18: {
              com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder subBuilder = com.tt.mariage.server.proto.UserDataProtos.Blob.Person.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addPerson(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isBookHotel_ = input.readBool();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              arrivalDate_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              departureDate_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              hasCar_ = input.readBool();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              freePlaces_ = input.readBytes();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              phoneNumber_ = input.readBytes();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              otherInfo_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string mail = 1;
      private java.lang.Object mail_ = "";
      public boolean hasMail() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getMail() {
        java.lang.Object ref = mail_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          mail_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setMail(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        mail_ = value;
        onChanged();
        return this;
      }
      public Builder clearMail() {
        bitField0_ = (bitField0_ & ~0x00000001);
        mail_ = getDefaultInstance().getMail();
        onChanged();
        return this;
      }
      void setMail(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        mail_ = value;
        onChanged();
      }
      
      // repeated .tutorial.Blob.Person person = 2;
      private java.util.List<com.tt.mariage.server.proto.UserDataProtos.Blob.Person> person_ =
        java.util.Collections.emptyList();
      private void ensurePersonIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          person_ = new java.util.ArrayList<com.tt.mariage.server.proto.UserDataProtos.Blob.Person>(person_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tt.mariage.server.proto.UserDataProtos.Blob.Person, com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder, com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder> personBuilder_;
      
      public java.util.List<com.tt.mariage.server.proto.UserDataProtos.Blob.Person> getPersonList() {
        if (personBuilder_ == null) {
          return java.util.Collections.unmodifiableList(person_);
        } else {
          return personBuilder_.getMessageList();
        }
      }
      public int getPersonCount() {
        if (personBuilder_ == null) {
          return person_.size();
        } else {
          return personBuilder_.getCount();
        }
      }
      public com.tt.mariage.server.proto.UserDataProtos.Blob.Person getPerson(int index) {
        if (personBuilder_ == null) {
          return person_.get(index);
        } else {
          return personBuilder_.getMessage(index);
        }
      }
      public Builder setPerson(
          int index, com.tt.mariage.server.proto.UserDataProtos.Blob.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.set(index, value);
          onChanged();
        } else {
          personBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setPerson(
          int index, com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.set(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addPerson(com.tt.mariage.server.proto.UserDataProtos.Blob.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(value);
          onChanged();
        } else {
          personBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addPerson(
          int index, com.tt.mariage.server.proto.UserDataProtos.Blob.Person value) {
        if (personBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePersonIsMutable();
          person_.add(index, value);
          onChanged();
        } else {
          personBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addPerson(
          com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addPerson(
          int index, com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder builderForValue) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.add(index, builderForValue.build());
          onChanged();
        } else {
          personBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllPerson(
          java.lang.Iterable<? extends com.tt.mariage.server.proto.UserDataProtos.Blob.Person> values) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          super.addAll(values, person_);
          onChanged();
        } else {
          personBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearPerson() {
        if (personBuilder_ == null) {
          person_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          personBuilder_.clear();
        }
        return this;
      }
      public Builder removePerson(int index) {
        if (personBuilder_ == null) {
          ensurePersonIsMutable();
          person_.remove(index);
          onChanged();
        } else {
          personBuilder_.remove(index);
        }
        return this;
      }
      public com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder getPersonBuilder(
          int index) {
        return getPersonFieldBuilder().getBuilder(index);
      }
      public com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder getPersonOrBuilder(
          int index) {
        if (personBuilder_ == null) {
          return person_.get(index);  } else {
          return personBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder> 
           getPersonOrBuilderList() {
        if (personBuilder_ != null) {
          return personBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(person_);
        }
      }
      public com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder addPersonBuilder() {
        return getPersonFieldBuilder().addBuilder(
            com.tt.mariage.server.proto.UserDataProtos.Blob.Person.getDefaultInstance());
      }
      public com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder addPersonBuilder(
          int index) {
        return getPersonFieldBuilder().addBuilder(
            index, com.tt.mariage.server.proto.UserDataProtos.Blob.Person.getDefaultInstance());
      }
      public java.util.List<com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder> 
           getPersonBuilderList() {
        return getPersonFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tt.mariage.server.proto.UserDataProtos.Blob.Person, com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder, com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder> 
          getPersonFieldBuilder() {
        if (personBuilder_ == null) {
          personBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.tt.mariage.server.proto.UserDataProtos.Blob.Person, com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder, com.tt.mariage.server.proto.UserDataProtos.Blob.PersonOrBuilder>(
                  person_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          person_ = null;
        }
        return personBuilder_;
      }
      
      // required bool isBookHotel = 3;
      private boolean isBookHotel_ ;
      public boolean hasIsBookHotel() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getIsBookHotel() {
        return isBookHotel_;
      }
      public Builder setIsBookHotel(boolean value) {
        bitField0_ |= 0x00000004;
        isBookHotel_ = value;
        onChanged();
        return this;
      }
      public Builder clearIsBookHotel() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isBookHotel_ = false;
        onChanged();
        return this;
      }
      
      // optional string arrivalDate = 4;
      private java.lang.Object arrivalDate_ = "";
      public boolean hasArrivalDate() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getArrivalDate() {
        java.lang.Object ref = arrivalDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          arrivalDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setArrivalDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        arrivalDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearArrivalDate() {
        bitField0_ = (bitField0_ & ~0x00000008);
        arrivalDate_ = getDefaultInstance().getArrivalDate();
        onChanged();
        return this;
      }
      void setArrivalDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        arrivalDate_ = value;
        onChanged();
      }
      
      // optional string departureDate = 5;
      private java.lang.Object departureDate_ = "";
      public boolean hasDepartureDate() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public String getDepartureDate() {
        java.lang.Object ref = departureDate_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          departureDate_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDepartureDate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        departureDate_ = value;
        onChanged();
        return this;
      }
      public Builder clearDepartureDate() {
        bitField0_ = (bitField0_ & ~0x00000010);
        departureDate_ = getDefaultInstance().getDepartureDate();
        onChanged();
        return this;
      }
      void setDepartureDate(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000010;
        departureDate_ = value;
        onChanged();
      }
      
      // required bool hasCar = 6;
      private boolean hasCar_ ;
      public boolean hasHasCar() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public boolean getHasCar() {
        return hasCar_;
      }
      public Builder setHasCar(boolean value) {
        bitField0_ |= 0x00000020;
        hasCar_ = value;
        onChanged();
        return this;
      }
      public Builder clearHasCar() {
        bitField0_ = (bitField0_ & ~0x00000020);
        hasCar_ = false;
        onChanged();
        return this;
      }
      
      // optional string freePlaces = 7;
      private java.lang.Object freePlaces_ = "";
      public boolean hasFreePlaces() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getFreePlaces() {
        java.lang.Object ref = freePlaces_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          freePlaces_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFreePlaces(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        freePlaces_ = value;
        onChanged();
        return this;
      }
      public Builder clearFreePlaces() {
        bitField0_ = (bitField0_ & ~0x00000040);
        freePlaces_ = getDefaultInstance().getFreePlaces();
        onChanged();
        return this;
      }
      void setFreePlaces(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        freePlaces_ = value;
        onChanged();
      }
      
      // optional string phoneNumber = 8;
      private java.lang.Object phoneNumber_ = "";
      public boolean hasPhoneNumber() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public String getPhoneNumber() {
        java.lang.Object ref = phoneNumber_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phoneNumber_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhoneNumber(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        phoneNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhoneNumber() {
        bitField0_ = (bitField0_ & ~0x00000080);
        phoneNumber_ = getDefaultInstance().getPhoneNumber();
        onChanged();
        return this;
      }
      void setPhoneNumber(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000080;
        phoneNumber_ = value;
        onChanged();
      }
      
      // optional string otherInfo = 9;
      private java.lang.Object otherInfo_ = "";
      public boolean hasOtherInfo() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public String getOtherInfo() {
        java.lang.Object ref = otherInfo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          otherInfo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setOtherInfo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        otherInfo_ = value;
        onChanged();
        return this;
      }
      public Builder clearOtherInfo() {
        bitField0_ = (bitField0_ & ~0x00000100);
        otherInfo_ = getDefaultInstance().getOtherInfo();
        onChanged();
        return this;
      }
      void setOtherInfo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000100;
        otherInfo_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.Blob)
    }
    
    static {
      defaultInstance = new Blob(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.Blob)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Blob_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Blob_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Blob_Person_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Blob_Person_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016userdata.proto\022\010tutorial\"\227\002\n\004Blob\022\014\n\004m" +
      "ail\030\001 \002(\t\022%\n\006person\030\002 \003(\0132\025.tutorial.Blo" +
      "b.Person\022\023\n\013isBookHotel\030\003 \002(\010\022\023\n\013arrival" +
      "Date\030\004 \001(\t\022\025\n\rdepartureDate\030\005 \001(\t\022\016\n\006has" +
      "Car\030\006 \002(\010\022\022\n\nfreePlaces\030\007 \001(\t\022\023\n\013phoneNu" +
      "mber\030\010 \001(\t\022\021\n\totherInfo\030\t \001(\t\032M\n\006Person\022" +
      "\020\n\010lastName\030\001 \002(\t\022\021\n\tfirstName\030\002 \002(\t\022\020\n\010" +
      "isInfant\030\003 \002(\010\022\014\n\004menu\030\004 \001(\tB-\n\033com.tt.m" +
      "ariage.server.protoB\016UserDataProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Blob_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Blob_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Blob_descriptor,
              new java.lang.String[] { "Mail", "Person", "IsBookHotel", "ArrivalDate", "DepartureDate", "HasCar", "FreePlaces", "PhoneNumber", "OtherInfo", },
              com.tt.mariage.server.proto.UserDataProtos.Blob.class,
              com.tt.mariage.server.proto.UserDataProtos.Blob.Builder.class);
          internal_static_tutorial_Blob_Person_descriptor =
            internal_static_tutorial_Blob_descriptor.getNestedTypes().get(0);
          internal_static_tutorial_Blob_Person_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Blob_Person_descriptor,
              new java.lang.String[] { "LastName", "FirstName", "IsInfant", "Menu", },
              com.tt.mariage.server.proto.UserDataProtos.Blob.Person.class,
              com.tt.mariage.server.proto.UserDataProtos.Blob.Person.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
